<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 1-->

<!DOCTYPE perifericos [
<!ELEMENT perifericos (#PCDATA)>
]>
<perifericos>impresora</perifericos>




<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 2-->

<!DOCTYPE perro [
<!ELEMENT perro (edad, nombre)>
<!ELEMENT edad (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
]>
<perro>
    <edad>8</edad>
    <nombre>Pancho</nombre>
</perro>



<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 3-->

<!DOCTYPE caballo [
<!ELEMENT caballo (nombre, raza, edad)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT raza (#PCDATA)>
<!ELEMENT edad EMPTY>
]>
<caballo>
    <nombre>Silvestre</nombre>
    <raza>Morgan</raza>
    <edad></edad>
</caballo>



<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 4-->

<!DOCTYPE mesa [
<!ELEMENT mesa ANY>
<!ELEMENT material (#PCDATA)>
<!ELEMENT color (#PCDATA)>
]>
<mesa> La mesa de 

    <material>madera </material> es de color

    <color>marrón</color>.


</mesa>


<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 5-->

<!DOCTYPE partes [
<!ELEMENT partes (secciones)>
<!ELEMENT secciones ANY> <!-- Se entiende que tras <secciones> podría venir cualquier cosa, por lo que resultaría válido considerar letras como elementos al mismo nivel de <secciones> o como hijas de secciones. Opto por la segunda alternativa al parecerme el código más claro.-->
<!ELEMENT letras (#PCDATA)>
]>
<partes>
    <secciones>
        <letras>abc</letras>
        <letras>MNT</letras>
        <letras>xyz</letras>
    </secciones>
</partes>

<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 6-->

<!DOCTYPE viajes [
<!ELEMENT viajes (austria, italia, francia)>
<!ELEMENT austria (ciudad+)>
<!ELEMENT italia (ciudad+)>
<!ELEMENT francia (ciudad+)>
<!ELEMENT ciudad (#PCDATA)>
]>

<viajes>
    <austria>
        <ciudad>Viena</ciudad>
    </austria>
    <italia>
        <ciudad>Florencia</ciudad>
        <ciudad>Roma</ciudad>
        <ciudad>Venecia</ciudad>
    </italia>
    <francia>
        <ciudad>París</ciudad>
    </francia>
</viajes>



<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 7-->

<!DOCTYPE ropa [
<!ELEMENT ropa (nombre, color*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT color (#PCDATA)>
]>
<ropa>
    <nombre>guante</nombre>
    <color>rojo</color>
    <color>blanco</color>    
</ropa>



<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 8-->

<!DOCTYPE productos [
<!ELEMENT productos (producto)*>
<!ELEMENT producto (identificacion, nombre)>
<!ELEMENT identificacion (#PCDATA | codigo | id)*>
<!ELEMENT codigo (#PCDATA)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
]>
<productos>
    <producto>
        <identificacion>
            <codigo>MAR264</codigo>
            Quedan 14 unidades.
        </identificacion>
        <nombre>martillo</nombre> 
    </producto>
    <producto>
        <identificacion>
            <codigo>DES387</codigo>
            <id>678984</id>
            No hay stock.
        </identificacion>
        <nombre>destornillador</nombre>
    </producto>
</productos>



<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 9-->


<!DOCTYPE forma_geometrica [
<!ELEMENT forma_geometrica (nombre, caracteristicas, numero_de_lados)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT caracteristicas (color,tipo)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT numero_de_lados (#PCDATA)>
]>
<forma_geometrica>
    <nombre>rombo</nombre>
    <caracteristicas>
        <color>naranja</color>
        <tipo>plana</tipo>
    </caracteristicas>
    <numero_de_lados>4</numero_de_lados>
</forma_geometrica>


<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 10-->

<!DOCTYPE lugares [
<!ELEMENT lugares ANY>
<!ELEMENT lugar (#PCDATA)>
]>
<lugares>En el <lugar>polo norte</lugar> hace mucho frío. Pero, en el
    <lugar>desierto del Sahara</lugar> hace mucho calor.</lugares>


<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 11-->

<!DOCTYPE ciudades [
<!ELEMENT ciudades (ciudad*)>
<!ELEMENT ciudad (nombre, capital?)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT capital EMPTY>
]>
<ciudades>
    <ciudad>
        <nombre>Buenos Aires</nombre>
        <capital/>
    </ciudad>
    <ciudad>
        <nombre>Liverpool</nombre>
    </ciudad>
    <ciudad>
        <nombre>Osaka</nombre>
    </ciudad>
    <ciudad>
        <nombre>Oslo</nombre>
        <capital/>
    </ciudad>
</ciudades>


<?xml version="1.0" encoding="UTF-8"?>

<!--Actividad 12-->

<!DOCTYPE socios [
<!ELEMENT socios (socio*)>
<!ELEMENT socio (numero?, clave?, nombre, edad?)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT clave (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT edad (#PCDATA)>
]>

<socios>
    <socio>
        <nombre>Ana</nombre>
        <edad>21</edad>
    </socio>
    <socio>
        <numero>598</numero>
        <nombre>Iker</nombre>
        <edad>19</edad>
    </socio>
    <socio>
        <clave>hY75Du</clave>
        <nombre>Iker</nombre>
    </socio>
</socios>


<?xml version="1.0" encoding="UTF-8"?>


<!--Actividad 13-->


<!DOCTYPE elementos [
<!ELEMENT elementos (pcdata*, any, vacio)>
<!ELEMENT pcdata (#PCDATA)>
<!ELEMENT any ANY>
<!ELEMENT vacio EMPTY>
]>
<elementos>
    <any/>
    <vacio/>
</elementos>